apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-pv-claim 
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gold
